"use client";

import { DatabaseSchemaGraph } from "@/components/database-schema-graph";

// Sample data matching the format you provided
const sampleSchemaData = {
  schemas: ["cron", "pg_toast", "public"],
  nodes: [
    {
      id: "cron.job",
      schema: "cron",
      name: "job",
      type: "BASE TABLE",
      primaryKey: [],
      columns: [
        {
          name: "jobid",
          type: "bigint",
          udt: "int8",
          nullable: false,
          default: "nextval('cron.jobid_seq'::regclass)",
          position: 1,
        },
        {
          name: "schedule",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 2,
        },
        {
          name: "command",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 3,
        },
        {
          name: "nodename",
          type: "text",
          udt: "text",
          nullable: false,
          default: "'localhost'::text",
          position: 4,
        },
        {
          name: "nodeport",
          type: "integer",
          udt: "int4",
          nullable: false,
          default: "inet_server_port()",
          position: 5,
        },
        {
          name: "database",
          type: "text",
          udt: "text",
          nullable: false,
          default: "current_database()",
          position: 6,
        },
        {
          name: "username",
          type: "text",
          udt: "text",
          nullable: false,
          default: "CURRENT_USER",
          position: 7,
        },
        {
          name: "active",
          type: "boolean",
          udt: "bool",
          nullable: false,
          default: "true",
          position: 8,
        },
        {
          name: "jobname",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 9,
        },
      ],
    },
    {
      id: "cron.job_run_details",
      schema: "cron",
      name: "job_run_details",
      type: "BASE TABLE",
      primaryKey: ["runid"],
      columns: [
        {
          name: "jobid",
          type: "bigint",
          udt: "int8",
          nullable: true,
          default: null,
          position: 1,
        },
        {
          name: "runid",
          type: "bigint",
          udt: "int8",
          nullable: false,
          default: "nextval('cron.runid_seq'::regclass)",
          position: 2,
        },
        {
          name: "job_pid",
          type: "integer",
          udt: "int4",
          nullable: true,
          default: null,
          position: 3,
        },
        {
          name: "database",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 4,
        },
        {
          name: "username",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 5,
        },
        {
          name: "command",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 6,
        },
        {
          name: "status",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 7,
        },
        {
          name: "return_message",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 8,
        },
        {
          name: "start_time",
          type: "timestamp with time zone",
          udt: "timestamptz",
          nullable: true,
          default: null,
          position: 9,
        },
        {
          name: "end_time",
          type: "timestamp with time zone",
          udt: "timestamptz",
          nullable: true,
          default: null,
          position: 10,
        },
      ],
    },
    {
      id: "public.account",
      schema: "public",
      name: "account",
      type: "BASE TABLE",
      primaryKey: ["id"],
      columns: [
        {
          name: "id",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 1,
        },
        {
          name: "accountId",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 2,
        },
        {
          name: "providerId",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 3,
        },
        {
          name: "userId",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 4,
        },
        {
          name: "accessToken",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 5,
        },
        {
          name: "refreshToken",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 6,
        },
        {
          name: "idToken",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 7,
        },
        {
          name: "accessTokenExpiresAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: true,
          default: null,
          position: 8,
        },
        {
          name: "refreshTokenExpiresAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: true,
          default: null,
          position: 9,
        },
        {
          name: "scope",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 10,
        },
        {
          name: "password",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 11,
        },
        {
          name: "createdAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: "CURRENT_TIMESTAMP",
          position: 12,
        },
        {
          name: "updatedAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: null,
          position: 13,
        },
      ],
    },
    {
      id: "public.project",
      schema: "public",
      name: "project",
      type: "BASE TABLE",
      primaryKey: ["id"],
      columns: [
        {
          name: "id",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 1,
        },
        {
          name: "name",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 2,
        },
        {
          name: "dbType",
          type: "USER-DEFINED",
          udt: "DbType",
          nullable: false,
          default: null,
          position: 3,
        },
        {
          name: "connectionUri",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 4,
        },
        {
          name: "createdAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: "CURRENT_TIMESTAMP",
          position: 5,
        },
        {
          name: "updatedAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: null,
          position: 6,
        },
        {
          name: "userId",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 7,
        },
      ],
    },
    {
      id: "public.session",
      schema: "public",
      name: "session",
      type: "BASE TABLE",
      primaryKey: ["id"],
      columns: [
        {
          name: "id",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 1,
        },
        {
          name: "expiresAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: null,
          position: 2,
        },
        {
          name: "token",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 3,
        },
        {
          name: "createdAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: "CURRENT_TIMESTAMP",
          position: 4,
        },
        {
          name: "updatedAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: null,
          position: 5,
        },
        {
          name: "ipAddress",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 6,
        },
        {
          name: "userAgent",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 7,
        },
        {
          name: "userId",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 8,
        },
      ],
    },
    {
      id: "public.user",
      schema: "public",
      name: "user",
      type: "BASE TABLE",
      primaryKey: ["id"],
      columns: [
        {
          name: "id",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 1,
        },
        {
          name: "name",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 2,
        },
        {
          name: "email",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 3,
        },
        {
          name: "emailVerified",
          type: "boolean",
          udt: "bool",
          nullable: false,
          default: null,
          position: 4,
        },
        {
          name: "image",
          type: "text",
          udt: "text",
          nullable: true,
          default: null,
          position: 5,
        },
        {
          name: "createdAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: "CURRENT_TIMESTAMP",
          position: 6,
        },
        {
          name: "updatedAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: null,
          position: 7,
        },
      ],
    },
    {
      id: "public.verification",
      schema: "public",
      name: "verification",
      type: "BASE TABLE",
      primaryKey: ["id"],
      columns: [
        {
          name: "id",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 1,
        },
        {
          name: "identifier",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 2,
        },
        {
          name: "value",
          type: "text",
          udt: "text",
          nullable: false,
          default: null,
          position: 3,
        },
        {
          name: "expiresAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: false,
          default: null,
          position: 4,
        },
        {
          name: "createdAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: true,
          default: "CURRENT_TIMESTAMP",
          position: 5,
        },
        {
          name: "updatedAt",
          type: "timestamp without time zone",
          udt: "timestamp",
          nullable: true,
          default: null,
          position: 6,
        },
      ],
    },
  ],
  edges: [
    {
      id: "account_userId_fkey",
      source: "public.account",
      sourceColumn: "userId",
      target: "public.user",
      targetColumn: "id",
      label: "userId → id",
    },
    {
      id: "project_userId_fkey",
      source: "public.project",
      sourceColumn: "userId",
      target: "public.user",
      targetColumn: "id",
      label: "userId → id",
    },
    {
      id: "session_userId_fkey",
      source: "public.session",
      sourceColumn: "userId",
      target: "public.user",
      targetColumn: "id",
      label: "userId → id",
    },
  ],
};

export default function SchemaGraphPage() {
  return (
    <div className="flex min-h-screen w-full flex-col p-6 md:p-10 bg-background">
      <div className="mx-auto w-full max-w-7xl space-y-8">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">
              Schema Visualization
            </h1>
            <p className="text-muted-foreground mt-1">
              Interactive visualization of your database schema showing tables,
              columns, and relationships.
            </p>
          </div>
        </div>

        {/* Graph Content */}
        <div className="h-[calc(100vh-200px)] w-full rounded-xl border bg-card shadow-sm">
          <DatabaseSchemaGraph data={sampleSchemaData} />
        </div>
      </div>
    </div>
  );
}
